# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=20.6.2
group=com.diontryban.ash_api
java_version=21

# Common
minecraft_version=1.20.6
mod_name=Ash API
mod_author=Trikzon
mod_id=ash_api
license=LGPL-3.0-or-later
credits=
description=An API that provides an abstraction layer between the APIs of the main Minecraft mod loaders: (Neo)Forge and Fabric.
minecraft_version_range=[1.20.6, 1.21)

# Fabric
fabric_version=0.98.0+1.20.6
fabric_loader_version=0.15.11
modmenu_version=10.0.0-beta.1

# Forge
forge_version=50.0.8
forge_loader_version_range=[50,)
forge_version_range=[50,)

# NeoForge
neoforge_version=20.6.48-beta
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false